links:
- product: firefox
  url: https://bugzilla.mozilla.org/show_bug.cgi?id=1543267
  results:
  - test: position-absolute-001.html
  - test: position-absolute-002.html
- product: firefox
  url: https://bugzilla.mozilla.org/show_bug.cgi?id=1500492
  results:
  - test: flex-minimum-width-flex-items-004.xht
  - test: flex-minimum-width-flex-items-006.xht