links:
- product: firefox
  results:
  - test: contain-size-flexbox-002.html
  url: https://bugzilla.mozilla.org/show_bug.cgi?id=1560420
- product: firefox
  results:
  - test: contain-size-grid-002.html
  url: https://bugzilla.mozilla.org/show_bug.cgi?id=1488878
- product: firefox
  results:
  - test: contain-layout-005.html
  url: https://bugzilla.mozilla.org/show_bug.cgi?id=1554327
