links:
- product: firefox
  results:
  - subtest: Test invalid MIME format "video/webm"
    test: mediasource-is-type-supported.html
  - subtest: Test invalid MIME format "video/webm;codecs=""
    test: mediasource-is-type-supported.html
  - subtest: Test invalid MIME format "video/webm;codecs="""
    test: mediasource-is-type-supported.html
  - subtest: Test invalid MIME format "video/webm;codecs="
    test: mediasource-is-type-supported.html
  - subtest: Test invalid MIME format "video/webm;"
    test: mediasource-is-type-supported.html
  - subtest: Test invalid MIME format "video/webm;codecs"
    test: mediasource-is-type-supported.html
  url: https://bugzilla.mozilla.org/show_bug.cgi?id=1191833
