links:
- product: firefox
  results:
  - test: selector-read-write-type-change-002.html
  url: https://bugzilla.mozilla.org/show_bug.cgi?id=312971
- product: firefox
  results:
  - test: floating-first-letter-05d0.html
  url: https://bugzilla.mozilla.org/show_bug.cgi?id=1495674
- product: firefox
  results:
  - test: selector-placeholder-shown-type-change-001.html
  url: https://bugzilla.mozilla.org/show_bug.cgi?id=1401657
