links:
- product: firefox
  results:
  - subtest: 10vh - computed
    test: shape-margin-001.html
  - subtest: 10vw - computed
    test: shape-margin-001.html
  - subtest: 10vmin - computed
    test: shape-margin-001.html
  - subtest: 10vmax - computed
    test: shape-margin-001.html
  url: https://bugzilla.mozilla.org/show_bug.cgi?id=1514429
