links:
- product: firefox
  results:
  - test: attachment-local-clipping-image-1.html
  - test: attachment-local-clipping-image-2.html
  - test: attachment-local-clipping-image-3.html
  url: https://bugzilla.mozilla.org/show_bug.cgi?id=1560210
