links:
- product: firefox
  results:
  - subtest: Navigating to new page should reset to "auto" and navigating back should
      restore and respect scroll restoration mode
    test: scroll-restoration-navigation-cross-origin.html
  url: https://bugzilla.mozilla.org/show_bug.cgi?id=1556685
