links:
- product: firefox
  results:
  - subtest: 'Legacy addStream(): Media stream stats references track stats'
    test: RTCPeerConnection-addStream.https.html
  url: https://bugzilla.mozilla.org/show_bug.cgi?id=1225720
