links:
- product: firefox
  results:
  - subtest: Anchor selection accounts for negative positioning.
    test: negative-layout-overflow.html
  url: https://bugzilla.mozilla.org/show_bug.cgi?id=1517287
- product: firefox
  results:
  - subtest: Line at edge of scrollport shouldn't jump visually when content is inserted
      before
    test: text-anchor-in-vertical-rl.html
  url: https://bugzilla.mozilla.org/show_bug.cgi?id=1447743
