links:
- product: firefox
  results:
  - subtest: <canvas><div id='target'> contents ok for element not being rendered
      ("<canvas><div id='target'>abc")
    test: getter.html
  url: https://bugzilla.mozilla.org/show_bug.cgi?id=1485076
